config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create] do
      resources :comments, only: [:create]
      resources :likes, only: [:create]
    end
  end
end

app/models/application_record.rb
# The ApplicationRecord class is the base class for all models in the application.
# It provides common functionality and configuration for database-backed models.
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# comment model
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_comment_counter

  private

  def update_comment_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
# like model
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_like_counter

  private

  def update_like_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
# post model
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_create :update_posts_counter

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end

  def recent_comments(limit = 5)
    comments.order(created_at: :desc).limit(limit)
  end
end

app/models/user.rb
# user model
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: :author_id
  has_many :comments
  has_many :likes

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts(limit = 3)
    posts.order(created_at: :desc).limit(limit)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :password, :password_confirmation, :name)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html { render :new }
    end
  end

  def create
    @comment = Comment.new(params.require(:comment).permit(:text))
    @comment.post = Post.find(params[:id])
    @comment.author = current_user

    respond_to do |format|
      format.html do
        if @comment.save
          redirect_to user_posts_path(user_id: current_user)
        else
          render :new
        end
      end
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:user_id])
    @like = Like.new(author: current_user, post: @post)

    if @like.save
      redirect_to user_posts_path(user_id: current_user)
    else
      flash.now[:error] = 'Error: Like could not be saved'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.includes(posts: :comments).find(params[:user_id])
  end

  def new
    @post = Post.new

    respond_to do |format|
      format.html { render :new }
    end
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to user_posts_path(user_id: current_user)
    else
      render :new
    end
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @user_post = @user.posts.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # @users = User.all
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
# The ApplicationHelper module provides utility methods that can be used
# across the entire application.
module ApplicationHelper
end

app/views/comments/new.html.erb
<%= form_with model: @comment, method: :post, url: user_post_comments_path do |f| %>

  <%= f.label :text %><br>
  <%= f.text_field :text %><br>

  <%= f.submit "Create Comment" %><br>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hello</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
        <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/likes/_add_like.html.erb
<%= form_with model: @like, url: user_posts_likes_path(user_id: @like.user.id, post_id: Post.find(params[:post_id])) do |f| %>
<%= f.submit "Like" %>
<% end %>

app/views/posts/index.html.erb
<section class="section">
    <article class="user_section_article image_and_user_container">
        <div class='image_container'>
            <img src="<%= @user.photo %>" class="" alt="">
        </div>
        <div class="user_section_information">
            <h2><%= @user.name %></h2>
            <p class='Post_absolute'>Number of posts: <%= @user.posts_counter %></p>
        </div>
    </article>
    <% @user.posts.each do |post| %>
        <div class='Post_container'>
          <div class='Post'>
              <a class="" href="<%= user_post_path(user_id: post.author_id, id: post.id) %>">
            <div>
                    <span class=""><%= post.title %></span>
                    <span class=""><%= post.text %></span>
                    <span class="Post_absolute">Comments:<%= post.comments_counter || 0 %>, Likes : <%= post.likes_counter || 0 %></span>
            </div>
                <% if post.recent_comments.present? %>
                    <div class="">
                            <% post.recent_comments.each do |comment| %>
                                <div class="">
                                    <div class=''> 
                                        <%= @user.name%> : <span><%= comment.text %></span>
                                    </div>
                                </div>
                            <% end %>
                    </div>
                <% else %>
                    <div class="">
                        <div>No comment</div>
                    </div>
                <% end %>
            </a>
          </div>
        </div>
    <% end %>
    <button>Pagination</button>
</section>

app/views/posts/new.html.erb
<section class = "section">
<%= form_with model: @post, url: user_posts_path , class: 'form' do |form| %>
<div>
    <%= form.label :title, "title:" %>
    <%= form.text_field :title, class: ''%>
</div>
<%= form.label :text, " " %>
<%= form.text_area :text, class: '', rows: 10 %>
<%= form.submit "post", class: '' %>
<% end %>
</section>

app/views/posts/show.html.erb
<section class="section">
    <div class="Post_container">
        <div class='Post'>
            <h1 class="post_title"><%= @post.title %></h1>
        <span >by <%= @user.name %></span>
        <span class='Post_absolute' >Comments : <%= @post.comments_counter || 0 %>, Likes : <%= @post.likes_counter || 0 %></span>

            <div class="">
                <%= @post.text %>
            </div>
        </div>
    </div>

    <div class="Post_container">
        <div class='Post'>
        <% if @post.comments.any? %>
            <% @post.comments.each do |comment| %>
                <div class="">
                    <div class=''> 
                    <%= @user.name %> : <span><%= @post.text %></span>
                    </div>
                </div>
            <% end %>
        <% else %>
            <div>No comments</div>
        <% end %>
        </div>
    </div>
</section>

app/views/users/index.html.erb
<section class='user_section section'>
<%= button_to 'Log out', destroy_user_session_path, method: :delete %>
<% @users.each do |user| %>
<article class="user_section_article image_and_user_container">
<div class='image_container'>
<img src="<%= user.photo %>" class="" alt="">
</div>
    <div class="user_section_information">
        <h2><%= link_to user.name, user_url(user) %></h2>
        <p class='Post_absolute'>Number of posts:<%=user.posts_counter || 0%></p>
    </div>
</article>
<% end %>
</section>

app/views/users/show.html.erb
<section class="section">
    <div class="user_section_article image_and_user_container">
        <div class="image_container">
            <img src="<%= @user.photo %>" alt="">
        </div>
        <div class="user_section_information">
            <h2><%= @user.name %></h2>
            <p class='Post_absolute'><%= link_to "Number of posts:", user_posts_url(@user.id) %> <%= @user.posts_counter || 0 %></p>
        </div>
    </div>

    <div class="Post_container">
       <div class='Post'>
            <h2>Bio</h2>
            <p><%= @user.bio %></p>
       </div>
    </div>

    <% if @user.recent_posts.any? %>
        <% @user.recent_posts.each do |post| %>
            <div class="Post_container">
                <div class='Post'>
                    <h2 class='user_post'><%= link_to "Post # ", user_post_url(@user.id, post.id) %><%= post.id %></h2>
                <h3><%= post.text %></h3>
                <div class='Post_absolute'>
                    <span>Comments:<%= post.comments_counter || 0 %> </span> 
                    <span>Likes:<%= post.likes_counter || 0 %></span>
                </div> 
                </div>   
            </div>
        <% end %>
        <div class='Post_container'>
           <a href="<%= user_posts_path(@user) %>" class="all_posts" id="all_posts">See all posts</a>
        </div>
        <% else %>
            <div class='Post_container'>
                <div class='Post'>
                    <p>No posts found.</p>
                </div>
            </div>
        <% end %>
</section>